name: 'snow_dbt_elementary'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"
vars:
  days_back: 14 
  anomaly_sensitivity: 1
  backfill_days: 2 

models:
  elementary:
    +schema: "elementary"
  snow_dbt_elementary:
    materialized: table
